import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import json
import hashlib
import os

OUT = "public/artifacts"
os.makedirs(OUT, exist_ok=True)

def sha(text):
    return hashlib.sha256(text.encode()).hexdigest()[:16]

# --- ENTITIES: People, Projects, Concepts, Tools ---
entities = [
    # People
    {"id": sha("Sarah Chen"), "human_readable_id": 0, "title": "SARAH CHEN", "type": "PERSON", "description": "VP of Engineering at Orion Labs. Leads the platform team and drives architecture decisions.", "text_unit_ids": ["tu0","tu1","tu2"]},
    {"id": sha("Marcus Rivera"), "human_readable_id": 1, "title": "MARCUS RIVERA", "type": "PERSON", "description": "Senior backend engineer. Owns the payment service and API gateway.", "text_unit_ids": ["tu1","tu3","tu4"]},
    {"id": sha("Priya Patel"), "human_readable_id": 2, "title": "PRIYA PATEL", "type": "PERSON", "description": "Frontend tech lead. Responsible for the React dashboard and design system.", "text_unit_ids": ["tu2","tu5","tu6"]},
    {"id": sha("James Kim"), "human_readable_id": 3, "title": "JAMES KIM", "type": "PERSON", "description": "DevOps engineer managing CI/CD pipelines, Kubernetes clusters, and monitoring.", "text_unit_ids": ["tu3","tu7"]},
    {"id": sha("Elena Volkov"), "human_readable_id": 4, "title": "ELENA VOLKOV", "type": "PERSON", "description": "Data scientist building ML models for fraud detection and recommendation engine.", "text_unit_ids": ["tu4","tu8","tu9"]},
    {"id": sha("David Okafor"), "human_readable_id": 5, "title": "DAVID OKAFOR", "type": "PERSON", "description": "Product manager for the enterprise tier. Coordinates between sales and engineering.", "text_unit_ids": ["tu5","tu10"]},
    {"id": sha("Aisha Nakamura"), "human_readable_id": 6, "title": "AISHA NAKAMURA", "type": "PERSON", "description": "QA lead running automated test suites and managing release quality gates.", "text_unit_ids": ["tu6","tu11"]},
    {"id": sha("Tom Bradley"), "human_readable_id": 7, "title": "TOM BRADLEY", "type": "PERSON", "description": "Security engineer responsible for penetration testing and compliance audits.", "text_unit_ids": ["tu7","tu12"]},
    # Projects / Systems
    {"id": sha("Payment Service"), "human_readable_id": 8, "title": "PAYMENT SERVICE", "type": "PROJECT", "description": "Core microservice handling Stripe integration, invoicing, and subscription billing.", "text_unit_ids": ["tu1","tu3","tu4","tu13"]},
    {"id": sha("API Gateway"), "human_readable_id": 9, "title": "API GATEWAY", "type": "PROJECT", "description": "Central gateway for rate limiting, auth, and request routing across microservices.", "text_unit_ids": ["tu1","tu7","tu14"]},
    {"id": sha("React Dashboard"), "human_readable_id": 10, "title": "REACT DASHBOARD", "type": "PROJECT", "description": "Customer-facing dashboard built with React and TypeScript. Shows analytics, billing, and settings.", "text_unit_ids": ["tu2","tu5","tu6"]},
    {"id": sha("Fraud Detection ML"), "human_readable_id": 11, "title": "FRAUD DETECTION ML", "type": "PROJECT", "description": "Machine learning pipeline using XGBoost to flag suspicious transactions in real-time.", "text_unit_ids": ["tu4","tu8","tu9"]},
    {"id": sha("Kubernetes Cluster"), "human_readable_id": 12, "title": "KUBERNETES CLUSTER", "type": "PROJECT", "description": "Production Kubernetes infrastructure on AWS EKS running all backend microservices.", "text_unit_ids": ["tu3","tu7"]},
    {"id": sha("Enterprise SSO"), "human_readable_id": 13, "title": "ENTERPRISE SSO", "type": "PROJECT", "description": "SAML/OIDC single sign-on integration for enterprise customers.", "text_unit_ids": ["tu10","tu12"]},
    # Concepts / Topics
    {"id": sha("Rate Limiting Bug"), "human_readable_id": 14, "title": "RATE LIMITING BUG", "type": "ISSUE", "description": "Critical bug where the API gateway rate limiter fails under concurrent requests above 10k RPS, causing 502 errors.", "text_unit_ids": ["tu1","tu7","tu14"]},
    {"id": sha("SOC2 Compliance"), "human_readable_id": 15, "title": "SOC2 COMPLIANCE", "type": "CONCEPT", "description": "Ongoing SOC2 Type II audit requiring encryption at rest, access logging, and incident response procedures.", "text_unit_ids": ["tu10","tu12"]},
    {"id": sha("Database Migration"), "human_readable_id": 16, "title": "DATABASE MIGRATION", "type": "CONCEPT", "description": "Migration from PostgreSQL 13 to PostgreSQL 16 for improved JSON performance and logical replication.", "text_unit_ids": ["tu3","tu13"]},
    {"id": sha("Q3 Launch"), "human_readable_id": 17, "title": "Q3 LAUNCH", "type": "EVENT", "description": "Major product launch scheduled for Q3 2026 including enterprise tier, SSO, and advanced analytics.", "text_unit_ids": ["tu5","tu10","tu11"]},
    {"id": sha("Stripe Integration"), "human_readable_id": 18, "title": "STRIPE INTEGRATION", "type": "CONCEPT", "description": "Payment processing via Stripe API for subscriptions, one-time charges, and invoice management.", "text_unit_ids": ["tu4","tu13"]},
    {"id": sha("CI/CD Pipeline"), "human_readable_id": 19, "title": "CI/CD PIPELINE", "type": "CONCEPT", "description": "GitHub Actions pipeline with automated testing, Docker builds, and Kubernetes deployments.", "text_unit_ids": ["tu3","tu7","tu11"]},
    {"id": sha("Design System"), "human_readable_id": 20, "title": "DESIGN SYSTEM", "type": "CONCEPT", "description": "Shared component library (Storybook) used by the React dashboard for consistent UI across the product.", "text_unit_ids": ["tu2","tu6"]},
    {"id": sha("Recommendation Engine"), "human_readable_id": 21, "title": "RECOMMENDATION ENGINE", "type": "PROJECT", "description": "Collaborative filtering engine that suggests relevant features and content to users based on usage patterns.", "text_unit_ids": ["tu8","tu9"]},
    {"id": sha("Slack"), "human_readable_id": 22, "title": "SLACK", "type": "TOOL", "description": "Primary team communication platform. All engineering discussions happen in #eng-general and project-specific channels.", "text_unit_ids": ["tu0","tu1"]},
    {"id": sha("Jira"), "human_readable_id": 23, "title": "JIRA", "type": "TOOL", "description": "Issue tracker for bugs, features, and sprint planning. Integrated with GitHub for PR tracking.", "text_unit_ids": ["tu0","tu14"]},
    {"id": sha("Notion"), "human_readable_id": 24, "title": "NOTION", "type": "TOOL", "description": "Documentation platform for architecture decisions, runbooks, onboarding guides, and meeting notes.", "text_unit_ids": ["tu0","tu13"]},
]

# --- RELATIONSHIPS ---
relationships = [
    {"id": sha("r0"), "human_readable_id": 0, "source": "SARAH CHEN", "target": "PAYMENT SERVICE", "description": "Sarah Chen approved the architecture for the payment service rewrite.", "weight": 0.9, "combined_degree": 8, "text_unit_ids": ["tu1"], "type": "RELATED"},
    {"id": sha("r1"), "human_readable_id": 1, "source": "MARCUS RIVERA", "target": "PAYMENT SERVICE", "description": "Marcus Rivera is the primary developer and owner of the payment service.", "weight": 1.0, "combined_degree": 7, "text_unit_ids": ["tu1","tu4"], "type": "RELATED"},
    {"id": sha("r2"), "human_readable_id": 2, "source": "MARCUS RIVERA", "target": "API GATEWAY", "description": "Marcus Rivera contributed the rate limiting middleware to the API gateway.", "weight": 0.8, "combined_degree": 6, "text_unit_ids": ["tu1"], "type": "RELATED"},
    {"id": sha("r3"), "human_readable_id": 3, "source": "PRIYA PATEL", "target": "REACT DASHBOARD", "description": "Priya Patel leads frontend development on the React dashboard.", "weight": 1.0, "combined_degree": 7, "text_unit_ids": ["tu2","tu5"], "type": "RELATED"},
    {"id": sha("r4"), "human_readable_id": 4, "source": "PRIYA PATEL", "target": "DESIGN SYSTEM", "description": "Priya Patel created and maintains the shared design system.", "weight": 0.9, "combined_degree": 5, "text_unit_ids": ["tu6"], "type": "RELATED"},
    {"id": sha("r5"), "human_readable_id": 5, "source": "JAMES KIM", "target": "KUBERNETES CLUSTER", "description": "James Kim manages the production Kubernetes cluster and deployment automation.", "weight": 1.0, "combined_degree": 6, "text_unit_ids": ["tu3","tu7"], "type": "RELATED"},
    {"id": sha("r6"), "human_readable_id": 6, "source": "JAMES KIM", "target": "CI/CD PIPELINE", "description": "James Kim built and maintains the CI/CD pipeline with GitHub Actions.", "weight": 0.9, "combined_degree": 5, "text_unit_ids": ["tu7"], "type": "RELATED"},
    {"id": sha("r7"), "human_readable_id": 7, "source": "ELENA VOLKOV", "target": "FRAUD DETECTION ML", "description": "Elena Volkov designed and trained the fraud detection ML model.", "weight": 1.0, "combined_degree": 6, "text_unit_ids": ["tu8","tu9"], "type": "RELATED"},
    {"id": sha("r8"), "human_readable_id": 8, "source": "ELENA VOLKOV", "target": "RECOMMENDATION ENGINE", "description": "Elena Volkov is building the collaborative filtering recommendation engine.", "weight": 0.8, "combined_degree": 5, "text_unit_ids": ["tu9"], "type": "RELATED"},
    {"id": sha("r9"), "human_readable_id": 9, "source": "DAVID OKAFOR", "target": "Q3 LAUNCH", "description": "David Okafor is the product manager coordinating the Q3 launch.", "weight": 1.0, "combined_degree": 5, "text_unit_ids": ["tu10"], "type": "RELATED"},
    {"id": sha("r10"), "human_readable_id": 10, "source": "DAVID OKAFOR", "target": "ENTERPRISE SSO", "description": "David Okafor defined requirements for enterprise SSO based on customer feedback.", "weight": 0.8, "combined_degree": 4, "text_unit_ids": ["tu10"], "type": "RELATED"},
    {"id": sha("r11"), "human_readable_id": 11, "source": "AISHA NAKAMURA", "target": "Q3 LAUNCH", "description": "Aisha Nakamura manages quality gates for the Q3 launch.", "weight": 0.8, "combined_degree": 4, "text_unit_ids": ["tu11"], "type": "RELATED"},
    {"id": sha("r12"), "human_readable_id": 12, "source": "TOM BRADLEY", "target": "SOC2 COMPLIANCE", "description": "Tom Bradley leads the security workstream for SOC2 compliance.", "weight": 1.0, "combined_degree": 5, "text_unit_ids": ["tu12"], "type": "RELATED"},
    {"id": sha("r13"), "human_readable_id": 13, "source": "TOM BRADLEY", "target": "ENTERPRISE SSO", "description": "Tom Bradley reviewed SSO implementation for security vulnerabilities.", "weight": 0.7, "combined_degree": 4, "text_unit_ids": ["tu12"], "type": "RELATED"},
    {"id": sha("r14"), "human_readable_id": 14, "source": "RATE LIMITING BUG", "target": "API GATEWAY", "description": "The rate limiting bug was discovered in the API gateway under high load.", "weight": 1.0, "combined_degree": 5, "text_unit_ids": ["tu14"], "type": "RELATED"},
    {"id": sha("r15"), "human_readable_id": 15, "source": "MARCUS RIVERA", "target": "RATE LIMITING BUG", "description": "Marcus Rivera is assigned to fix the rate limiting bug.", "weight": 0.9, "combined_degree": 5, "text_unit_ids": ["tu14"], "type": "RELATED"},
    {"id": sha("r16"), "human_readable_id": 16, "source": "PAYMENT SERVICE", "target": "STRIPE INTEGRATION", "description": "The payment service uses Stripe for all billing operations.", "weight": 1.0, "combined_degree": 5, "text_unit_ids": ["tu4","tu13"], "type": "RELATED"},
    {"id": sha("r17"), "human_readable_id": 17, "source": "DATABASE MIGRATION", "target": "PAYMENT SERVICE", "description": "The database migration affects the payment service's transaction tables.", "weight": 0.8, "combined_degree": 4, "text_unit_ids": ["tu13"], "type": "RELATED"},
    {"id": sha("r18"), "human_readable_id": 18, "source": "JAMES KIM", "target": "DATABASE MIGRATION", "description": "James Kim is executing the PostgreSQL migration with zero-downtime strategy.", "weight": 0.9, "combined_degree": 4, "text_unit_ids": ["tu3"], "type": "RELATED"},
    {"id": sha("r19"), "human_readable_id": 19, "source": "FRAUD DETECTION ML", "target": "PAYMENT SERVICE", "description": "The fraud detection model scores transactions processed by the payment service.", "weight": 0.9, "combined_degree": 5, "text_unit_ids": ["tu8"], "type": "RELATED"},
    {"id": sha("r20"), "human_readable_id": 20, "source": "SARAH CHEN", "target": "Q3 LAUNCH", "description": "Sarah Chen is the executive sponsor for the Q3 launch.", "weight": 0.9, "combined_degree": 6, "text_unit_ids": ["tu10"], "type": "RELATED"},
    {"id": sha("r21"), "human_readable_id": 21, "source": "REACT DASHBOARD", "target": "DESIGN SYSTEM", "description": "The React dashboard consumes components from the shared design system.", "weight": 0.8, "combined_degree": 4, "text_unit_ids": ["tu6"], "type": "RELATED"},
    {"id": sha("r22"), "human_readable_id": 22, "source": "KUBERNETES CLUSTER", "target": "PAYMENT SERVICE", "description": "The payment service runs on the Kubernetes cluster as a deployment.", "weight": 0.7, "combined_degree": 4, "text_unit_ids": ["tu3"], "type": "RELATED"},
    {"id": sha("r23"), "human_readable_id": 23, "source": "KUBERNETES CLUSTER", "target": "API GATEWAY", "description": "The API gateway is deployed on the Kubernetes cluster.", "weight": 0.7, "combined_degree": 4, "text_unit_ids": ["tu7"], "type": "RELATED"},
    {"id": sha("r24"), "human_readable_id": 24, "source": "SARAH CHEN", "target": "MARCUS RIVERA", "description": "Sarah Chen mentors Marcus Rivera and reviews his architecture proposals.", "weight": 0.7, "combined_degree": 6, "text_unit_ids": ["tu1"], "type": "RELATED"},
    {"id": sha("r25"), "human_readable_id": 25, "source": "ELENA VOLKOV", "target": "STRIPE INTEGRATION", "description": "Elena Volkov uses Stripe transaction data as training features for the fraud model.", "weight": 0.6, "combined_degree": 4, "text_unit_ids": ["tu9"], "type": "RELATED"},
    {"id": sha("r26"), "human_readable_id": 26, "source": "CI/CD PIPELINE", "target": "KUBERNETES CLUSTER", "description": "The CI/CD pipeline deploys containers to the Kubernetes cluster.", "weight": 0.9, "combined_degree": 4, "text_unit_ids": ["tu7"], "type": "RELATED"},
    {"id": sha("r27"), "human_readable_id": 27, "source": "AISHA NAKAMURA", "target": "CI/CD PIPELINE", "description": "Aisha Nakamura integrated automated test suites into the CI/CD pipeline.", "weight": 0.8, "combined_degree": 4, "text_unit_ids": ["tu11"], "type": "RELATED"},
    {"id": sha("r28"), "human_readable_id": 28, "source": "SOC2 COMPLIANCE", "target": "ENTERPRISE SSO", "description": "SOC2 compliance requires SSO for all enterprise customer access.", "weight": 0.8, "combined_degree": 4, "text_unit_ids": ["tu12"], "type": "RELATED"},
    {"id": sha("r29"), "human_readable_id": 29, "source": "PRIYA PATEL", "target": "Q3 LAUNCH", "description": "Priya Patel is building the enterprise dashboard features for Q3 launch.", "weight": 0.7, "combined_degree": 4, "text_unit_ids": ["tu5"], "type": "RELATED"},
    {"id": sha("r30"), "human_readable_id": 30, "source": "SARAH CHEN", "target": "SLACK", "description": "Sarah Chen posts architecture updates and decisions in the #eng-general Slack channel.", "weight": 0.5, "combined_degree": 4, "text_unit_ids": ["tu0"], "type": "RELATED"},
    {"id": sha("r31"), "human_readable_id": 31, "source": "RATE LIMITING BUG", "target": "JIRA", "description": "The rate limiting bug is tracked as PLATFORM-1247 in Jira.", "weight": 0.7, "combined_degree": 3, "text_unit_ids": ["tu14"], "type": "RELATED"},
    {"id": sha("r32"), "human_readable_id": 32, "source": "DATABASE MIGRATION", "target": "NOTION", "description": "The database migration runbook is documented in Notion.", "weight": 0.6, "combined_degree": 3, "text_unit_ids": ["tu13"], "type": "RELATED"},
]

# --- DOCUMENTS ---
documents = [
    {"id": sha("doc0"), "human_readable_id": 0, "title": "Slack: #eng-general - Architecture Discussion", "text": "Team discussion about the payment service rewrite, API gateway improvements, and Q3 launch planning. Sarah Chen outlined the new microservice boundaries. Marcus Rivera raised concerns about the rate limiter.", "text_unit_ids": ["tu0","tu1"]},
    {"id": sha("doc1"), "human_readable_id": 1, "title": "Slack: #payments - Stripe Migration Thread", "text": "Marcus Rivera and Elena Volkov discussed the Stripe API v3 migration and its impact on fraud detection scoring. The team decided to batch transactions for ML inference.", "text_unit_ids": ["tu4","tu13"]},
    {"id": sha("doc2"), "human_readable_id": 2, "title": "Slack: #frontend - Dashboard Redesign", "text": "Priya Patel shared mockups for the enterprise dashboard. Design system components were discussed. The team agreed on a phased rollout starting with analytics pages.", "text_unit_ids": ["tu2","tu5","tu6"]},
    {"id": sha("doc3"), "human_readable_id": 3, "title": "Jira: PLATFORM-1247 - Rate Limiting Failure", "text": "Bug report: API gateway rate limiter fails above 10k RPS with concurrent requests. Priority: Critical. Assigned to Marcus Rivera. Root cause: Redis connection pool exhaustion under sustained load.", "text_unit_ids": ["tu14"]},
    {"id": sha("doc4"), "human_readable_id": 4, "title": "Jira: PLATFORM-1198 - PostgreSQL 16 Migration", "text": "Epic for migrating from PostgreSQL 13 to 16. Includes schema compatibility testing, logical replication setup, and zero-downtime cutover plan. Owner: James Kim.", "text_unit_ids": ["tu3","tu13"]},
    {"id": sha("doc5"), "human_readable_id": 5, "title": "Jira: ML-302 - Fraud Model v3 Training", "text": "Feature ticket for training fraud detection model v3 with new Stripe webhook features. Elena Volkov estimated 2 weeks for data pipeline updates and model retraining.", "text_unit_ids": ["tu8","tu9"]},
    {"id": sha("doc6"), "human_readable_id": 6, "title": "Notion: Payment Service Architecture", "text": "Architecture decision record for the payment service. Documents the choice of event sourcing pattern, Stripe webhook handling, and idempotency guarantees. Authored by Marcus Rivera, reviewed by Sarah Chen.", "text_unit_ids": ["tu1","tu4","tu13"]},
    {"id": sha("doc7"), "human_readable_id": 7, "title": "Notion: Kubernetes Runbook", "text": "Operational runbook for the production Kubernetes cluster. Covers scaling procedures, disaster recovery, monitoring alerts, and incident response. Maintained by James Kim.", "text_unit_ids": ["tu3","tu7"]},
    {"id": sha("doc8"), "human_readable_id": 8, "title": "Notion: SOC2 Compliance Checklist", "text": "Comprehensive checklist for SOC2 Type II audit. Covers encryption, access controls, logging, incident response, and vendor management. Led by Tom Bradley.", "text_unit_ids": ["tu10","tu12"]},
    {"id": sha("doc9"), "human_readable_id": 9, "title": "Notion: Q3 Launch Plan", "text": "Product launch plan for Q3 2026. Includes enterprise SSO, advanced analytics dashboard, and fraud detection v3. Milestones, dependencies, and risk assessment. Authored by David Okafor.", "text_unit_ids": ["tu5","tu10","tu11"]},
]

# --- TEXT UNITS ---
text_units = [
    {"id": "tu0", "human_readable_id": 0, "text": "Sarah Chen posted in #eng-general: 'Team, we need to finalize the microservice boundaries before Q3. The payment service, API gateway, and fraud detection need clear ownership. Let's discuss in Thursday's arch review.' Multiple tools are in play - Slack for discussions, Jira for tracking, Notion for documentation.", "n_tokens": 52, "document_ids": [sha("doc0")], "entity_ids": [sha("Sarah Chen"), sha("Slack"), sha("Jira"), sha("Notion")], "relationship_ids": [sha("r30")]},
    {"id": "tu1", "human_readable_id": 1, "text": "Marcus Rivera responded to Sarah's thread: 'I've been seeing 502s on the API gateway when we hit 10k RPS. The rate limiter isn't handling concurrent requests well. I think the Redis connection pool is getting exhausted.' Sarah replied: 'That's critical - file a P0 in Jira and let's get it fixed before Q3.'", "n_tokens": 58, "document_ids": [sha("doc0"), sha("doc6")], "entity_ids": [sha("Sarah Chen"), sha("Marcus Rivera"), sha("Payment Service"), sha("API Gateway"), sha("Rate Limiting Bug")], "relationship_ids": [sha("r0"), sha("r1"), sha("r2"), sha("r24")]},
    {"id": "tu2", "human_readable_id": 2, "text": "Priya Patel shared in #frontend: 'Here are the mockups for the enterprise dashboard. I've used our design system components for consistency. The analytics page uses the new chart components I built last sprint. Let me know your thoughts on the layout.'", "n_tokens": 44, "document_ids": [sha("doc2")], "entity_ids": [sha("Priya Patel"), sha("React Dashboard"), sha("Design System")], "relationship_ids": [sha("r3"), sha("r4")]},
    {"id": "tu3", "human_readable_id": 3, "text": "James Kim updated PLATFORM-1198: 'PostgreSQL 16 migration plan is ready. Phase 1: Set up logical replication from PG13 to PG16. Phase 2: Run dual-write for 48 hours. Phase 3: Cutover with < 30s downtime. The payment service tables are the highest risk - they have the most foreign key constraints.'", "n_tokens": 55, "document_ids": [sha("doc4"), sha("doc7")], "entity_ids": [sha("James Kim"), sha("Kubernetes Cluster"), sha("Payment Service"), sha("Database Migration"), sha("CI/CD Pipeline")], "relationship_ids": [sha("r5"), sha("r6"), sha("r18")]},
    {"id": "tu4", "human_readable_id": 4, "text": "Elena Volkov commented on ML-302: 'The new Stripe webhook data gives us 12 additional features for fraud scoring. I'm seeing a 15% improvement in precision on the test set. We need Marcus to update the payment service to forward the new webhook fields.'", "n_tokens": 46, "document_ids": [sha("doc1"), sha("doc5")], "entity_ids": [sha("Elena Volkov"), sha("Marcus Rivera"), sha("Payment Service"), sha("Fraud Detection ML"), sha("Stripe Integration")], "relationship_ids": [sha("r1"), sha("r7"), sha("r16"), sha("r19")]},
    {"id": "tu5", "human_readable_id": 5, "text": "David Okafor created the Q3 launch plan in Notion: 'Key deliverables: 1) Enterprise SSO (SAML + OIDC), 2) Advanced analytics dashboard, 3) Fraud detection v3. Dependencies: frontend needs design system updates, backend needs PG16 migration complete. Target: August 15th.'", "n_tokens": 48, "document_ids": [sha("doc2"), sha("doc9")], "entity_ids": [sha("David Okafor"), sha("Priya Patel"), sha("React Dashboard"), sha("Q3 Launch")], "relationship_ids": [sha("r3"), sha("r9"), sha("r29")]},
    {"id": "tu6", "human_readable_id": 6, "text": "Priya Patel documented the design system update in Notion: 'Added 8 new components for enterprise features: DataGrid, FilterPanel, ExportDialog, RoleSelector, AuditLog, UsageChart, TeamSwitcher, SSOConfig. All components follow our accessibility guidelines and support dark mode.'", "n_tokens": 42, "document_ids": [sha("doc2")], "entity_ids": [sha("Priya Patel"), sha("React Dashboard"), sha("Design System")], "relationship_ids": [sha("r4"), sha("r21")]},
    {"id": "tu7", "human_readable_id": 7, "text": "James Kim updated the Kubernetes runbook: 'Added section on auto-scaling for the API gateway pods. Current config: min 3, max 20 replicas. HPA triggers at 70% CPU. Also documented the new Datadog monitors for payment service latency and error rates.'", "n_tokens": 44, "document_ids": [sha("doc7")], "entity_ids": [sha("James Kim"), sha("Kubernetes Cluster"), sha("API Gateway"), sha("CI/CD Pipeline")], "relationship_ids": [sha("r5"), sha("r6"), sha("r23"), sha("r26")]},
    {"id": "tu8", "human_readable_id": 8, "text": "Elena Volkov presented fraud model results: 'Model v3 achieves 94.2% precision and 89.7% recall. False positive rate dropped from 3.1% to 1.8%. The model processes transactions in < 50ms p99, well within the payment service SLA.'", "n_tokens": 42, "document_ids": [sha("doc5")], "entity_ids": [sha("Elena Volkov"), sha("Fraud Detection ML"), sha("Payment Service")], "relationship_ids": [sha("r7"), sha("r19")]},
    {"id": "tu9", "human_readable_id": 9, "text": "Elena discussed the recommendation engine in #data-science: 'The collaborative filtering model is showing promising results. Users who received recommendations had 23% higher engagement. Next step: integrate with the dashboard for personalized feature suggestions.'", "n_tokens": 38, "document_ids": [sha("doc5")], "entity_ids": [sha("Elena Volkov"), sha("Recommendation Engine"), sha("Fraud Detection ML"), sha("Stripe Integration")], "relationship_ids": [sha("r8"), sha("r25")]},
    {"id": "tu10", "human_readable_id": 10, "text": "David Okafor updated the launch plan: 'Enterprise customers are requesting SSO urgently. Acme Corp and GlobalTech both have it as a blocker for annual renewal. Tom is reviewing the SAML implementation for SOC2 compliance. Sarah approved fast-tracking this.'", "n_tokens": 42, "document_ids": [sha("doc8"), sha("doc9")], "entity_ids": [sha("David Okafor"), sha("Sarah Chen"), sha("Enterprise SSO"), sha("Q3 Launch"), sha("SOC2 Compliance")], "relationship_ids": [sha("r9"), sha("r10"), sha("r20")]},
    {"id": "tu11", "human_readable_id": 11, "text": "Aisha Nakamura posted test results: 'Regression suite is green. Added 47 new E2E tests for the enterprise dashboard. Coverage is at 82%. I've integrated the test suite into the CI/CD pipeline - all PRs now require passing E2E tests before merge.'", "n_tokens": 40, "document_ids": [sha("doc9")], "entity_ids": [sha("Aisha Nakamura"), sha("Q3 Launch"), sha("CI/CD Pipeline")], "relationship_ids": [sha("r11"), sha("r27")]},
    {"id": "tu12", "human_readable_id": 12, "text": "Tom Bradley completed the security review: 'SSO implementation passed pen testing. Found and fixed one medium-severity CSRF vulnerability in the SAML callback. SOC2 evidence collection is 78% complete. Remaining items: vendor questionnaires and disaster recovery test.'", "n_tokens": 40, "document_ids": [sha("doc8")], "entity_ids": [sha("Tom Bradley"), sha("SOC2 Compliance"), sha("Enterprise SSO")], "relationship_ids": [sha("r12"), sha("r13"), sha("r28")]},
    {"id": "tu13", "human_readable_id": 13, "text": "Marcus Rivera documented the payment architecture in Notion: 'We use event sourcing for all payment state transitions. Stripe webhooks are processed idempotently using event IDs. The PG16 migration will improve JSON query performance for our event store by 3x.'", "n_tokens": 40, "document_ids": [sha("doc1"), sha("doc4"), sha("doc6")], "entity_ids": [sha("Payment Service"), sha("Stripe Integration"), sha("Database Migration"), sha("Notion")], "relationship_ids": [sha("r16"), sha("r17"), sha("r32")]},
    {"id": "tu14", "human_readable_id": 14, "text": "PLATFORM-1247 bug details: 'Root cause identified - Redis connection pool set to 50 max connections, but each rate limit check holds a connection for ~10ms. At 10k RPS, we need at least 100 connections. Fix: increase pool size and add connection timeout. Marcus Rivera is working on the patch.'", "n_tokens": 48, "document_ids": [sha("doc3")], "entity_ids": [sha("Rate Limiting Bug"), sha("API Gateway"), sha("Marcus Rivera"), sha("Jira")], "relationship_ids": [sha("r14"), sha("r15"), sha("r31")]},
]

# --- COMMUNITIES ---
communities = [
    {"id": 0, "human_readable_id": 0, "community": 0, "level": 0, "title": "Platform Infrastructure", "entity_ids": [sha("James Kim"), sha("Kubernetes Cluster"), sha("CI/CD Pipeline"), sha("Database Migration"), sha("API Gateway")], "relationship_ids": [sha("r5"), sha("r6"), sha("r18"), sha("r23"), sha("r26")], "text_unit_ids": ["tu3","tu7"], "period": "2026-Q2", "size": 5},
    {"id": 1, "human_readable_id": 1, "community": 1, "level": 0, "title": "Payment & Billing", "entity_ids": [sha("Marcus Rivera"), sha("Payment Service"), sha("Stripe Integration"), sha("Rate Limiting Bug")], "relationship_ids": [sha("r1"), sha("r2"), sha("r14"), sha("r15"), sha("r16"), sha("r17")], "text_unit_ids": ["tu1","tu4","tu13","tu14"], "period": "2026-Q2", "size": 4},
    {"id": 2, "human_readable_id": 2, "community": 2, "level": 0, "title": "ML & Data Science", "entity_ids": [sha("Elena Volkov"), sha("Fraud Detection ML"), sha("Recommendation Engine")], "relationship_ids": [sha("r7"), sha("r8"), sha("r19"), sha("r25")], "text_unit_ids": ["tu4","tu8","tu9"], "period": "2026-Q2", "size": 3},
    {"id": 3, "human_readable_id": 3, "community": 3, "level": 0, "title": "Frontend & Design", "entity_ids": [sha("Priya Patel"), sha("React Dashboard"), sha("Design System")], "relationship_ids": [sha("r3"), sha("r4"), sha("r21")], "text_unit_ids": ["tu2","tu5","tu6"], "period": "2026-Q2", "size": 3},
    {"id": 4, "human_readable_id": 4, "community": 4, "level": 0, "title": "Enterprise & Compliance", "entity_ids": [sha("David Okafor"), sha("Tom Bradley"), sha("Enterprise SSO"), sha("SOC2 Compliance"), sha("Q3 Launch")], "relationship_ids": [sha("r9"), sha("r10"), sha("r12"), sha("r13"), sha("r28")], "text_unit_ids": ["tu10","tu11","tu12"], "period": "2026-Q2", "size": 5},
    {"id": 5, "human_readable_id": 5, "community": 5, "level": 1, "title": "Orion Labs Engineering", "entity_ids": [sha("Sarah Chen"), sha("Slack"), sha("Jira"), sha("Notion")], "relationship_ids": [sha("r0"), sha("r20"), sha("r24"), sha("r30"), sha("r31"), sha("r32")], "text_unit_ids": ["tu0","tu1","tu10"], "period": "2026-Q2", "size": 4},
]

# --- COMMUNITY REPORTS ---
community_reports = [
    {"id": sha("cr0"), "human_readable_id": 0, "community": 0, "level": 0, "title": "Platform Infrastructure", "summary": "The Platform Infrastructure community centers on James Kim's management of the production Kubernetes cluster and CI/CD pipeline. A critical PostgreSQL 13-to-16 migration is underway with a zero-downtime strategy. The API gateway runs as a Kubernetes deployment with auto-scaling configured.", "full_content": "# Platform Infrastructure\n\nThis community encompasses the core infrastructure that powers Orion Labs' backend services.\n\n## Key Findings\n\n1. James Kim is the single point of responsibility for both Kubernetes operations and CI/CD pipeline maintenance, creating a bus factor risk.\n2. The PostgreSQL migration from v13 to v16 is being executed with a careful three-phase approach (replication, dual-write, cutover) to minimize downtime.\n3. Auto-scaling is configured for the API gateway (3-20 replicas, 70% CPU trigger) but other services may need similar treatment before Q3 launch.", "rank": 7.5, "rank_explanation": "Critical infrastructure with high impact on all services", "findings": [{"summary": "Single point of failure in infrastructure management", "explanation": "James Kim manages both Kubernetes and CI/CD, creating a bus factor risk."}, {"summary": "Database migration in progress", "explanation": "PostgreSQL 13 to 16 migration using zero-downtime strategy with logical replication."}], "full_content_json": "", "period": "2026-Q2", "size": 5},
    {"id": sha("cr1"), "human_readable_id": 1, "community": 1, "level": 0, "title": "Payment & Billing", "summary": "The Payment & Billing community is centered on the payment service owned by Marcus Rivera. A critical rate limiting bug (PLATFORM-1247) in the API gateway is being addressed. The service uses event sourcing with Stripe integration and is affected by the ongoing database migration.", "full_content": "# Payment & Billing\n\nThis community encompasses the payment processing infrastructure.\n\n## Key Findings\n\n1. A critical rate limiting bug causes 502 errors above 10k RPS due to Redis connection pool exhaustion.\n2. The payment service uses event sourcing for state management with Stripe webhook processing.\n3. The PostgreSQL 16 migration will improve JSON query performance 3x for the event store.", "rank": 8.5, "rank_explanation": "Revenue-critical service with active P0 bug", "findings": [{"summary": "Critical rate limiting bug at 10k RPS", "explanation": "Redis connection pool exhaustion causes 502 errors. Fix: increase pool size from 50 to 100+ connections."}, {"summary": "Event sourcing architecture with Stripe", "explanation": "Payment state transitions use event sourcing with idempotent Stripe webhook processing."}], "full_content_json": "", "period": "2026-Q2", "size": 4},
    {"id": sha("cr2"), "human_readable_id": 2, "community": 2, "level": 0, "title": "ML & Data Science", "summary": "Elena Volkov leads the ML initiatives including fraud detection (94.2% precision, < 50ms p99 latency) and a recommendation engine showing 23% engagement improvement. The fraud model v3 leverages new Stripe webhook features.", "full_content": "# ML & Data Science\n\nThis community covers machine learning systems at Orion Labs.\n\n## Key Findings\n\n1. Fraud model v3 achieves 94.2% precision and 89.7% recall with false positive rate of 1.8%.\n2. The recommendation engine shows 23% higher user engagement in A/B tests.\n3. Both models depend on payment service data, creating a coupling that needs monitoring.", "rank": 7.0, "rank_explanation": "High business impact with measurable improvements", "findings": [{"summary": "Fraud model v3 significantly improves detection", "explanation": "15% precision improvement, false positive rate dropped from 3.1% to 1.8%."}, {"summary": "Recommendation engine drives engagement", "explanation": "23% higher engagement for users receiving personalized recommendations."}], "full_content_json": "", "period": "2026-Q2", "size": 3},
    {"id": sha("cr3"), "human_readable_id": 3, "community": 3, "level": 0, "title": "Frontend & Design", "summary": "Priya Patel leads frontend development with a React dashboard and shared design system. Eight new enterprise components were added. The team follows accessibility guidelines and supports dark mode across all components.", "full_content": "# Frontend & Design\n\nThis community encompasses the user-facing application layer.\n\n## Key Findings\n\n1. The design system now includes 8 new enterprise-focused components.\n2. All components follow accessibility guidelines and support dark mode.\n3. The enterprise dashboard is being built in phases, starting with analytics.", "rank": 6.5, "rank_explanation": "Customer-facing with direct Q3 launch impact", "findings": [{"summary": "Design system expanded for enterprise", "explanation": "8 new components: DataGrid, FilterPanel, ExportDialog, RoleSelector, AuditLog, UsageChart, TeamSwitcher, SSOConfig."}, {"summary": "Phased dashboard rollout", "explanation": "Enterprise dashboard rolling out analytics pages first, then billing and settings."}], "full_content_json": "", "period": "2026-Q2", "size": 3},
    {"id": sha("cr4"), "human_readable_id": 4, "community": 4, "level": 0, "title": "Enterprise & Compliance", "summary": "The Enterprise & Compliance community manages the Q3 launch, SOC2 audit (78% complete), and enterprise SSO. Enterprise customers Acme Corp and GlobalTech have SSO as a renewal blocker. Security review passed with one CSRF fix.", "full_content": "# Enterprise & Compliance\n\nThis community covers enterprise features and compliance requirements.\n\n## Key Findings\n\n1. SOC2 Type II audit evidence collection is 78% complete with vendor questionnaires and DR test remaining.\n2. Enterprise SSO passed security pen testing with one medium-severity CSRF fix.\n3. Two major customers have SSO as a contract renewal blocker, creating urgency.", "rank": 8.0, "rank_explanation": "Revenue impact from enterprise renewals and compliance requirements", "findings": [{"summary": "SSO is a revenue blocker", "explanation": "Acme Corp and GlobalTech both require SSO for annual renewal. Fast-tracked by Sarah Chen."}, {"summary": "SOC2 audit nearing completion", "explanation": "78% complete. Remaining: vendor questionnaires and disaster recovery test."}], "full_content_json": "", "period": "2026-Q2", "size": 5},
    {"id": sha("cr5"), "human_readable_id": 5, "community": 5, "level": 1, "title": "Orion Labs Engineering", "summary": "Sarah Chen leads the engineering organization at Orion Labs. The team uses Slack for communication, Jira for issue tracking, and Notion for documentation. Information flows across these platforms are connected through NexusGraph.", "full_content": "# Orion Labs Engineering\n\nThis is the top-level community representing the engineering organization.\n\n## Key Findings\n\n1. Sarah Chen serves as VP of Engineering and executive sponsor for the Q3 launch.\n2. Three primary tools (Slack, Jira, Notion) fragment knowledge across the organization.\n3. NexusGraph connects these data sources to provide a unified view of engineering activity.", "rank": 9.0, "rank_explanation": "Top-level organizational community", "findings": [{"summary": "Information fragmentation across tools", "explanation": "Engineering knowledge is scattered across Slack, Jira, and Notion, requiring cross-platform search."}, {"summary": "Strong leadership alignment", "explanation": "Sarah Chen provides clear architectural direction and sponsors key initiatives."}], "full_content_json": "", "period": "2026-Q2", "size": 4},
]

# --- Write parquet files ---
def write_parquet(data, filename):
    df = pd.DataFrame(data)
    if "findings" in df.columns:
        df["findings"] = df["findings"].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)
    pq.write_table(pa.Table.from_pandas(df), os.path.join(OUT, filename))
    print(f"Wrote {filename} ({len(data)} rows)")

write_parquet(entities, "entities.parquet")
write_parquet(relationships, "relationships.parquet")
write_parquet(documents, "documents.parquet")
write_parquet(text_units, "text_units.parquet")
write_parquet(communities, "communities.parquet")
write_parquet(community_reports, "community_reports.parquet")

print("\nDone! All parquet files written to public/artifacts/")
